function fds = fds_init
%
%  FDS_INIT  Initializes a standard data structure.  
%
%  Usage: fds = fds_init;
%
%  Description:
%
%    Initializes the flight data structure 
%    for use in SIDPAC.  All data fields
%    are initialized to an empty matrix.
%
%  Input:
%    
%    None
%
%  Output:
%
%    fds = flight data structure in standard configuration.
%
%

%
%    Calls:
%      None
%
%    Author:  Eugene A. Morelli
%
%    History:  
%      8 Jan 2004 - Created and debugged, EAM.
%
%  Copyright (C) 2006  Eugene A. Morelli
%
%  This program carries no warranty, not even the implied 
%  warranty of merchantability or fitness for a particular purpose.  
%
%  Please email bug reports or suggestions for improvements to:
%
%      e.a.morelli@nasa.gov
%

%
%  Initialize the flight data structure (fds).  
%
fds=struct('t',[],...
           'fdata',[]);
%
%  Experiment information.
%
fds.aircraft=[];
fds.maneuver=[];
fds.test_date=[];
fds.pilot=[];
%
%  Default variable descriptions.
%
fds.vardesc={'  time  (sec) ';...
             '  airspeed  (ft/sec) ';...
             '  sideslip angle  (deg) ';...
             '  angle of attack  (deg) ';...
             '  roll rate  (deg/sec) ';...
             '  pitch rate  (deg/sec) ';...
             '  yaw rate  (deg/sec) ';...
             '  roll angle  (deg) ';...
             '  pitch angle  (deg) ';...
             '  heading angle  (deg) ';...
             '  ax  (g) ';...
             '  ay  (g) ';...
             '  az  (g) ';...
             '  elevator  (deg) ';...
             '  aileron  (deg) ';...
             '  rudder  (deg) ';...
             '  te flap  (deg) ';...
             '  le flap  (deg) ';...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             '  dynamic pressure  (lbf/ft2) ';...
             '  mach number ';...
             '  air density  (slug/ft3) ';...
             '  altitude  (ft) ';...
             '  lon stick  (in) ';...
             '  lat stick  (in) ';...
             '  rdr pedal  (in) ';...
             '  throttle  (deg) ';...
             [];...
             [];...
             [];...
             '  thrust  (lbf) ';...
             [];...
             [];...
             [];...
             '  roll accel  (deg/sec2) ';...
             '  pitch accel  (deg/sec2) ';...
             '  yaw accel  (deg/sec2) ';...
             '  x cg position  (in) ';...
             '  y cg position  (in) ';...
             '  z cg position  (in) ';...
             '  mass  (slug) ';...
             '  Ixx  (slug-ft2) ';...
             '  Iyy  (slug-ft2) ';...
             '  Izz  (slug-ft2) ';...
             '  Ixz  (slug-ft2) ';...
             '  meas ax  (g) ';...
             '  meas ay  (g) ';...
             '  meas az  (g) ';...
             '  alpha dot  (deg/sec) ';...
             '  beta dot  (deg/sec) ';...
             '  roll tv  (deg) ';...
             '  pitch tv  (deg) ';...
             '  yaw tv  (deg) ';...
             '  CX ';...
             '  CY ';...
             '  CZ ';...
             '  Cl ';...
             '  Cm ';...
             '  Cn ';...
             '  CD ';...
             '  CYw ';...
             '  CL ';...
             '  CT ';...
             '  phat ';...
             '  qhat ';...
             '  rhat ';...
             '  u  (ft/sec) ';...
             '  v  (ft/sec) ';...
             '  w  (ft/sec) ';...
             '  wing area  (ft2) ';...
             '  wing span  (ft) ';...
             '  wing mac  (ft) ';...
             '  meas sideslip angle  (deg) ';...
             '  meas angle of attack  (deg) ';...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             [];...
             []};
%
%  Default variable labels.
%
fds.varlab={'  time ';...
            '  V ';...
            '  beta ';...
            '  alpha ';...
            '  p ';...
            '  q ';...
            '  r ';...
            '  phi ';...
            '  the ';...
            '  psi ';...
            '  ax ';...
            '  ay ';...
            '  az ';...
            '  el ';...
            '  ail ';...
            '  rdr ';...
            '  tef ';...
            '  lef ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '  qbar ';...
            '  mach ';...
            '  rho ';...
            '  alt ';...
            '  lonstk ';...
            '  latstk ';...
            '  rudped ';...
            '  thtl ';...
            '      ';...
            '      ';...
            '      ';...
            '  thrust ';...
            '      ';...
            '      ';...
            '      ';...
            '  pdot ';...
            '  qdot ';...
            '  rdot ';...
            '  xcg ';...
            '  ycg ';...
            '  zcg ';...
            '  mass ';...
            '  Ixx ';...
            '  Iyy ';...
            '  Izz ';...
            '  Ixz ';...
            '  axm ';...
            '  aym ';...
            '  azm ';...
            '  alpdot ';...
            '  btadot ';...
            '  ptv ';...
            '  qtv ';...
            '  rtv ';...
            '  CX ';...
            '  CY ';...
            '  CZ ';...
            '  Cl ';...
            '  Cm ';...
            '  Cn ';...
            '  CD ';...
            '  CYw ';...
            '  CL ';...
            '  CT ';...
            '  phat ';...
            '  qhat ';...
            '  rhat ';...
            '  u ';...
            '  v ';...
            '  w ';...
            '  sarea ';...
            '  bspan ';...
            '  cbar ';...
            '  betam ';...
            '  alpham ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      ';...
            '      '};
%
%  Default variable units.
%
fds.varunits={' (sec) ';...
              ' (fps) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (dps) ';...
              ' (dps) ';...
              ' (dps) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (g) ';...
              ' (g) ';...
              ' (g) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (deg) ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              ' (psf) ';...
              '   ';...
              ' (slug/ft3) ';...
              ' (ft) ';...
              ' (in) ';...
              ' (in) ';...
              ' (in) ';...
              ' (deg) ';...
              '   ';...
              '   ';...
              '   ';...
              ' (lbf) ';...
              '   ';...
              '   ';...
              '   ';...
              ' (dps2) ';...
              ' (dps2) ';...
              ' (dps2) ';...
              ' (in) ';...
              ' (in) ';...
              ' (in) ';...
              ' (slug) ';...
              ' (slug-ft2) ';...
              ' (slug-ft2) ';...
              ' (slug-ft2) ';...
              ' (slug-ft2) ';...
              ' (g) ';...
              ' (g) ';...
              ' (g) ';...
              ' (dps) ';...
              ' (dps) ';...
              ' (deg) ';...
              ' (deg) ';...
              ' (deg) ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              ' (fps) ';...
              ' (fps) ';...
              ' (fps) ';...
              ' (ft2) ';...
              ' (ft) ';...
              ' (ft) ';...
              ' (deg) ';...
              ' (deg) ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   ';...
              '   '};
%
%  Aircraft wing geometry.
%
fds.sarea=[];
fds.bspan=[];
fds.cbar=[];
%
%  User notes.
%
fds.notes=[];
%
%  Record when fds was created.
%
fds.created=datestr(now);
return
